# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-04 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('L', 'Like'), ('LP', 'Like Profile')], max_length=5),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'Liked'), ('LP', 'Liked Profile'), ('C', 'Commented'), ('S', 'Also Commented')], max_length=5),
        ),
    ]
