# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_institute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_title',
            new_name='home',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='usp',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='url',
            new_name='website',
        ),
    ]
