# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-04 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20170304_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='want_to_do',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='what do you want to do?'),
        ),
    ]
